# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 03:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('published', models.BooleanField()),
                ('news', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'News items',
            },
        ),
    ]
