# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piece', to='photologue.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='FanartGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fanart', to='photologue.Gallery')),
            ],
        ),
    ]
