# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('extras', '0002_auto_20160817_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanartGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fanart', to='photologue.Gallery')),
            ],
        ),
    ]
