# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_fanartgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('media', 'Media coverage'), ('mycontrib', "Things I've done"), ('interesting', 'Interesting things'), ('fanworks', 'Fan works (not art)')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('desc', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='fanartgallery',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='fanart',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fanpiece', to='photologue.Photo'),
        ),
        migrations.AlterField(
            model_name='fanart',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='FanartGallery',
        ),
    ]
