# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_auto_20160821_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanart',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
