# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20160302_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ImageField(blank=True, upload_to='')),
                ('alt_text', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comic',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='comic_page',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='url',
        ),
        migrations.AddField(
            model_name='comic',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comicfile',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Comic'),
        ),
    ]
