# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_auto_20160304_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicfile',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='comicfile',
            name='page',
            field=models.ImageField(blank=True, upload_to='comix/'),
        ),
    ]
