# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_auto_20160305_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='comic',
            name='next',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='prev',
        ),
        migrations.AlterField(
            model_name='comic',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
