# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_auto_20160402_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='published',
            field=models.BooleanField(default=False, verbose_name='is published?'),
        ),
    ]
