# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_auto_20160408_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cid',
            field=models.IntegerField(default=0, verbose_name='Comic number'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='guest',
            field=models.BooleanField(default=False, verbose_name='Is guest/special comic'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='published',
            field=models.BooleanField(default=False, verbose_name='is published'),
        ),
    ]
