# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0011_guestcomic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcomic',
            name='ref_comic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcomic', to='comics.Comic'),
        ),
        migrations.AlterField(
            model_name='guestcomic',
            name='type',
            field=models.CharField(choices=[('guest', 'Guest comic'), ('special', 'Special item'), ('art', 'Filler art'), ('ad', 'Advertisement')], max_length=10),
        ),
    ]
