# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0012_auto_20160807_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcomic',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
