# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comics', '0009_auto_20160408_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booknum', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('end_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ending comic+', to='comics.Comic')),
                ('start_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Starting comic+', to='comics.Comic')),
            ],
        ),
    ]
