# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='published',
            field=models.BooleanField(default=False, verbose_name='is published?'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='booknum',
            field=models.IntegerField(default=1, verbose_name='Book number'),
        ),
    ]
