# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20160409_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='end_id',
        ),
    ]
