# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castentry',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='text',
            field=models.TextField(),
        ),
    ]
