# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_auto_20160302_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castentry',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/cast/'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/cast/'),
        ),
    ]
