# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_auto_20160302_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castentry',
            options={'verbose_name_plural': 'Cast entries'},
        ),
        migrations.AlterField(
            model_name='castentry',
            name='category',
            field=models.CharField(choices=[('humans', 'humans'), ('werewolves', 'werewolves'), ('hunters', 'hunters'), ('sorcerors', 'sorcerors')], max_length=20),
        ),
    ]
